"""HalfCheetah at 100 Hz: three continuous rollouts of a trained policy.

Generated by the companion gen-half-cheetah-dataset repository. Each split is
one uninterrupted trace (train 20 min, valid 3 min, test 3 min) with no
injected noise, sampled at 100 Hz so the joint velocities are resolved. One
``.npz`` per split holds ``obs`` (T+1, 17) and ``act`` (T, 6); ``act[t]`` is
the zero-order-held control that takes ``obs[t]`` to ``obs[t+1]``.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from train_srnn.data.task import TASKS, TraceTask


@TASKS.register("cheetah100")
@TASKS.register("cheetah100_act")
class Cheetah100Task(TraceTask):
    """Next-step prediction of the 17 observation channels (23 with actions)."""

    def _read_split(self, data_dir: Path, split: str) -> np.ndarray:
        with np.load(Path(data_dir) / f"{split}.npz") as z:
            obs = z["obs"].astype(np.float32)
            act = z["act"].astype(np.float32)
        if self.cfg.include_actions:
            return np.concatenate([obs[:len(act)], act], axis=1)
        return obs

    def read_traces(self, data_dir: Path):
        traces = [self._read_split(data_dir, s) for s in ("train", "valid", "test")]
        # Every rollout starts from a standstill and takes a few seconds to
        # reach cruising speed; drop that so the statistics describe the gait.
        n_skip = int(round(self.cfg.skip_transient_s * self.cfg.sample_rate_hz))
        return tuple(t[n_skip:] for t in traces)
