#!/usr/bin/env python3
"""Verify exported production MATLAB fixtures against the actual trainable cell.

Usage: uv run python scripts/verify_matlab_parity.py /private/tmp/srnn-parity
Fixtures are generated by scripts/matlab/export_srnn_parity.m through MATLAB MCP.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import numpy as np
from scipy.io import loadmat
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from train_srnn.models.srnn_cell import SRNNCell, SRNNConfig, piecewise_sigmoid

CONDITIONS = ("no_adaptation", "sfa1_std1", "sfa3_std2")


def tensor(value):
    return torch.as_tensor(np.asarray(value).copy(), dtype=torch.float64)


def load_cell(path: Path):
    data = loadmat(path, squeeze_me=False)
    n = data["W"].shape[0]
    a, b = data["n_a"].ravel(), data["n_b"].ravel()
    config = SRNNConfig(num_units=n, dales=False, n_a_E=int(a[0]), n_a_I=int(a[1]),
                        n_b_E=int(b[0]), n_b_I=int(b[1]), solver="sra1",
                        h=float(data["h"].item()), ode_unfolds=1,
                        S_a=float(data["S_a"].item()))
    export = {"W_init": tensor(data["W"]), "sparsity_mask": torch.ones(n, n),
              "dales_sign": torch.cat((torch.ones(n//2), -torch.ones(n-n//2)))}
    cell = SRNNCell([config], input_size=1, rmt_exports=[export]).double()
    with torch.no_grad():
        cell.W_raw.copy_(tensor(data["W"]).unsqueeze(0))
        cell.log_W_raw_gain.zero_()
        cell.W_in.fill_(0.1)
        cell.W_in_gain.fill_(1)
        cell.a_0_vec.copy_(tensor(data["a0"]).reshape(1,n))
        cell.a_0_scalar.zero_()
        def positive(name, value):
            target = getattr(cell, name)
            value = tensor(value).expand_as(target)
            # Stable inverse softplus, including very large heterogeneous taus.
            target.copy_(value + torch.log(-torch.expm1(-value)))
        positive("isp_tau_d_vec", data["tau_d"].item())
        cell.log_tau_d_gain.zero_()
        for q, side in enumerate(("E", "I")):
            if a[q]:
                positive(f"isp_tau_a_{side}_vec", data[f"tau_a_{side}"])
                positive(f"isp_c_{side}_vec", data["c"].ravel()[q])
                getattr(cell, f"log_tau_a_{side}_gain").zero_()
                getattr(cell, f"log_c_{side}_gain").zero_()
            if b[q]:
                for kind in ("rec", "rel"):
                    positive(f"isp_tau_b_{kind}_{side}_vec", data[f"tau_b_{kind}_{side}"])
                    getattr(cell, f"log_tau_b_{kind}_{side}_gain").zero_()
    return cell, data


def error(actual, expected, *, atol, rtol=0):
    a = actual.detach().cpu().numpy() if isinstance(actual, torch.Tensor) else actual
    e = np.asarray(expected)
    np.testing.assert_allclose(a, e.reshape(a.shape), atol=atol, rtol=rtol)
    return float(np.max(np.abs(a-e.reshape(a.shape))))


@torch.no_grad()
def verify_fixture(path: Path, trajectories=True, make_plot=False):
    cell, data = load_cell(path)
    state = tensor(data["state0"]).reshape(1,1,-1)
    a_e,a_i,b_e,b_i,x = cell.unpack_state(state)
    rhs,rate,gain = cell._rhs(x,a_e,a_i,b_e,b_i,torch.zeros_like(x),cell.hoist())
    derivative = cell.pack_state(rhs[1],rhs[2],rhs[3],rhs[4],rhs[0])
    report = {"derivative_max_abs":error(derivative,data["derivative0"],atol=1e-12,rtol=1e-10),
              "rate_max_abs":error(rate,data["rate0"],atol=1e-12),
              "synaptic_max_abs":error(rate*gain,data["synaptic0"],atol=1e-12)}
    probe=tensor(data["probe_state"]).reshape(1,1,-1)
    pa_e,pa_i,pb_e,pb_i,px=cell.unpack_state(probe)
    pd,pr,pg=cell._rhs(px,pa_e,pa_i,pb_e,pb_i,torch.zeros_like(px),cell.hoist())
    report["probe_derivative_max_abs"]=error(cell.pack_state(pd[1],pd[2],pd[3],pd[4],pd[0]),
                                              data["probe_derivative"],atol=1e-12,rtol=1e-10)
    report["probe_rate_max_abs"]=error(pr,data["probe_rate"],atol=1e-12)
    report["probe_synaptic_max_abs"]=error(pr*pg,data["probe_synaptic"],atol=1e-12)
    activated = piecewise_sigmoid(tensor(data["activation_x"]).reshape(1,1,-1)-cell._a_0().unsqueeze(1),
                                  S_a=float(data["S_a"].item()))
    report["activation_max_abs"] = error(activated,data["activation_y"],atol=1e-12)
    _, updated = cell(torch.zeros(1,1,dtype=torch.float64),state)
    report["one_step_max_abs"] = error(updated,data["state_one_step"],atol=1e-12,rtol=1e-10)
    if trajectories and "unforced" in data:
        cell.h, cell.ode_unfolds = 0.01, 4
        W = cell.hoist()
        for kind in ("unforced", "driven"):
            state = tensor(data["state0"]).reshape(1,1,-1)
            states = [state[0,0].numpy().copy()]
            rates, synaptic = [], []
            diag = cell.get_diagnostics(state)
            rates.append(diag["r"][0,0].numpy()); synaptic.append(diag["br"][0,0].numpy())
            for i in range(len(data[kind])-1):
                amp = 0. if kind=="unforced" else float(data["input_amplitude"].ravel()[i])
                output,state=cell(torch.tensor([[amp]],dtype=torch.float64),state,W)
                diag=cell.get_diagnostics(state)
                states.append(state[0,0].numpy().copy())
                rates.append(diag["r"][0,0].numpy()); synaptic.append(output[0,0].numpy())
            for label, values in (("state",states),("rate",rates),("synaptic",synaptic)):
                expected=data[kind] if label=="state" else data[f"{kind}_{label}"]
                report[f"{kind}_{label}_max_abs"]=error(np.asarray(values),expected,atol=1e-7)
            if make_plot:
                import matplotlib
                matplotlib.use("Agg")
                import matplotlib.pyplot as plt
                fig,axes=plt.subplots(2,1,figsize=(9,5),sharex=True)
                t=data["time"].ravel()
                axes[0].plot(t,data[f"{kind}_rate"].mean(1),label="MATLAB",lw=2)
                axes[0].plot(t,np.asarray(rates).mean(1),"--",label="PyTorch",lw=1)
                axes[0].set_ylabel("Mean raw rate"); axes[0].legend()
                axes[1].plot(t,np.max(np.abs(np.asarray(states)-data[kind]),axis=1))
                axes[1].set(xlabel="Time (s)",ylabel="Maximum state error")
                fig.tight_layout(); fig.savefig(path.parent/f"parity_{kind}.png",dpi=180); plt.close(fig)
        report["contraction_ratio"]=float(data["contraction_ratio"].item())
        assert report["contraction_ratio"] < 1
        report["refinement_hz"]=data["refinement_hz"].ravel().tolist()
        report["refinement_error"]=data["refinement_error"].ravel().tolist()
        assert np.all(np.diff(report["refinement_error"])<0)
    return report


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixture_dir",type=Path)
    parser.add_argument("--short",action="store_true",help="Only activation, RHS, and one step")
    args=parser.parse_args()
    torch.set_num_threads(1)
    results={name:verify_fixture(args.fixture_dir/f"{name}.mat",not args.short,not args.short) for name in CONDITIONS}
    report={"torch_version":torch.__version__,"dtype":"float64","conditions":results}
    out=args.fixture_dir/("parity_short.json" if args.short else "parity_report.json")
    out.write_text(json.dumps(report,indent=2)+"\n")
    print(json.dumps(report,indent=2))


if __name__ == "__main__":
    main()
